### ISSUE TITLE
allow user and project from different domain 

### ISSUE THREAD

**Issue by majewsky** [FujitsuEnablingSoftwareTechnologyGmbH/logstash-output-monasca_log_api#1]
The `domain_id` configuration option is used [both to locate the user and the project](https://github.com/FujitsuEnablingSoftwareTechnologyGmbH/logstash-output-monasca_log_api/blob/e9214b1c8d1ae6d75e33bd21c0f3579678b8f0a6/lib/logstash/outputs/keystone/keystone_client.rb#L61-L82). However, it is possible that user and project are in different domains, in which case two different domain IDs would need to be specified.

**Comment by kornicameister** [comment]
@kejc87 you are the expert here, could you test and write back to @majewsky ?

**Comment by witekest** [comment]
@majewsky We are in the process of submitting the plugin to the logstash-plugins repository. Could you please add this issue as a comment to [this pull request](https://github.com/logstash-plugins/logstash-output-monasca_log_api/pull/1)? Thanks.
